language: ruby
sudo: false
before_install: gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rspec
matrix:
  fast_finish: true
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - ruby-head
  allow_failures:
    - rvm: ruby-head
cache: bundler
