language: ruby

sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

before_install: gem install bundler
script:
  - COVER=1 bundle exec rspec
  - bundle exec rubocop

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

cache: bundler
